name: Automated Release

on:
  push:
    branches: [main, develop]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
          standalone: true

      - name: Initialize Node.js Runtime
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml" # <--- Ajouté pour fixer l'erreur de store path

      - name: Install Project Dependencies
        run: pnpm install --frozen-lockfile

      - name: Execute Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Build Workflow
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{ "tag": "v${{ steps.semantic.outputs.new_release_version }}" }'
